"""add_refresh_token_selector

Revision ID: b465250cc7d4
Revises: 7372701253f2
Create Date: 2026-06-02 14:26:57.068404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b465250cc7d4'
down_revision: Union[str, Sequence[str], None] = '7372701253f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('selector', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_selector'), 'refresh_tokens', ['selector'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_selector'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'selector')
    # ### end Alembic commands ###
